=== BuddhaNexus/buddhanexus/metadata/schemas/files.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Files",
    "description": "Language specific list of source textual files",
    "type": "array",
    "items": {
        "additionalProperties": false,
        "required": [
            "category",
            "textname",
            "filenr",
            "displayName"
        ],
        "properties": {
            "category": { "type": "string" },
            "textname": { "type": "string" },
            "filename": { "type": "string" },
            "filenr": { "type": "integer" },

            "link": { "type": "string" },
            "link2": { "type": "string" },
            "source": { "type": "string" },
            "alt_filename": { "type": "string" },
            "displayName": { "type": "string" },

            "chapters": { 
                "type": "array",
                "description": "Only for Sanskrit???"
        }
        }
    }
}

=== BuddhaNexus/buddhanexus/data/en-files.json
[
  {
    "displayName": "Brahmajāla Sutta",
    "textname": "Dn 1",
    "filename": "en-dn1",
    "category": "dn",
    "filenr": 1
  },
  {
    "displayName": "Sāmaññaphala Sutta",
    "textname": "Dn 2",
    "filename": "en-dn2",
    "category": "dn",
    "filenr": 2
  },
  {
    "displayName": "Ambaṭṭha Sutta",
    "textname": "Dn 3",
    "filename": "en-dn3",
    "category": "dn",
    "filenr": 3
  },
  {
    "displayName": "Soṇadaṇḍa Sutta",
    "textname": "Dn 4",
    "filename": "en-dn4",
    "category": "dn",
    "filenr": 4
  },
  {
    "displayName": "Kūṭadanta Sutta",
    "textname": "Dn 5",
    "filename": "en-dn5",
    "category": "dn",
    "filenr": 5
  },
  {
    "displayName": "Mahāli Sutta",
    "textname": "Dn 6",
    "filename": "en-dn6",
    "category": "dn",
    "filenr": 6
  },
  {
    "displayName": "Jāliya Sutta",
    "textname": "Dn 7",
    "filename": "en-dn7",
    "category": "dn",
    "filenr": 7
  },
  {
    "displayName": "Mahāsīhanāda Sutta",
    "textname": "Dn 8",
    "filename": "en-dn8",
    "category": "dn",
    "filenr": 8
  },
  {
    "displayName": "Poṭṭhapāda Sutta",
    "textname": "Dn 9",
    "filename": "en-dn9",
    "category": "dn",
    "filenr": 9
  },
  {
    "displayName": "Subha Sutta",
    "textname": "Dn 10",
    "filename": "en-dn10",
    "category": "dn",
    "filenr": 10
  },
  {
    "displayName": "Kevaṭṭa Sutta",
    "textname": "Dn 11",
    "filename": "en-dn11",
    "category": "dn",
    "filenr": 11
  },
  {
    "displayName": "Lohicca Sutta",
    "textname": "Dn 12",
    "filename": "en-dn12",
    "category": "dn",
    "filenr": 12
  },
  {
    "displayName": "Tevijja Sutta",
    "textname": "Dn 13",
    "filename": "en-dn13",
    "category": "dn",
    "filenr": 13
  },
  {
    "displayName": "Mahāpadāna Sutta",
    "textname": "Dn 14",
    "filename": "en-dn14",
    "category": "dn",
    "filenr": 14
  },
  {
    "displayName": "Mahānidāna Sutta",
    "textname": "Dn 15",
    "filename": "en-dn15",
    "category": "dn",
    "filenr": 15
  },
  {
    "displayName": "Mahāparinibbāna Sutta",
    "textname": "Dn 16",
    "filename": "en-dn16",
    "category": "dn",
    "filenr": 16
  },
  {
    "displayName": "Mahāsudassana Sutta",
    "textname": "Dn 17",
    "filename": "en-dn17",
    "category": "dn",
    "filenr": 17
  },
  {
    "displayName": "Janavasabha Sutta",
    "textname": "Dn 18",
    "filename": "en-dn18",
    "category": "dn",
    "filenr": 18
  },
  {
    "displayName": "Mahāgovinda Sutta",
    "textname": "Dn 19",
    "filename": "en-dn19",
    "category": "dn",
    "filenr": 19
  },
  {
    "displayName": "Mahāsamaya Sutta",
    "textname": "Dn 20",
    "filename": "en-dn20",
    "category": "dn",
    "filenr": 20
  },
  {
    "displayName": "Sakkapañha Sutta",
    "textname": "Dn 21",
    "filename": "en-dn21",
    "category": "dn",
    "filenr": 21
  },
  {
    "displayName": "Mahāsatipaṭṭhāna Sutta",
    "textname": "Dn 22",
    "filename": "en-dn22",
    "category": "dn",
    "filenr": 22
  },
  {
    "displayName": "Pāyāsi Sutta",
    "textname": "Dn 23",
    "filename": "en-dn23",
    "category": "dn",
    "filenr": 23
  },
  {
    "displayName": "Pāthika Sutta",
    "textname": "Dn 24",
    "filename": "en-dn24",
    "category": "dn",
    "filenr": 24
  },
  {
    "displayName": "Udumbarika Sutta",
    "textname": "Dn 25",
    "filename": "en-dn25",
    "category": "dn",
    "filenr": 25
  },
  {
    "displayName": "Cakkavatti Sutta",
    "textname": "Dn 26",
    "filename": "en-dn26",
    "category": "dn",
    "filenr": 26
  },
  {
    "displayName": "Aggañña Sutta",
    "textname": "Dn 27",
    "filename": "en-dn27",
    "category": "dn",
    "filenr": 27
  },
  {
    "displayName": "Sampasādanīya Sutta",
    "textname": "Dn 28",
    "filename": "en-dn28",
    "category": "dn",
    "filenr": 28
  },
  {
    "displayName": "Pāsādika Sutta",
    "textname": "Dn 29",
    "filename": "en-dn29",
    "category": "dn",
    "filenr": 29
  },
  {
    "displayName": "Lakkhaṇa Sutta",
    "textname": "Dn 30",
    "filename": "en-dn30",
    "category": "dn",
    "filenr": 30
  },
  {
    "displayName": "Siṅgāla Sutta",
    "textname": "Dn 31",
    "filename": "en-dn31",
    "category": "dn",
    "filenr": 31
  },
  {
    "displayName": "Āṭānāṭiya Sutta",
    "textname": "Dn 32",
    "filename": "en-dn32",
    "category": "dn",
    "filenr": 32
  },
  {
    "displayName": "Saṅgīti Sutta",
    "textname": "Dn 33",
    "filename": "en-dn33",
    "category": "dn",
    "filenr": 33
  },
  {
    "displayName": "Dasuttara Sutta",
    "textname": "Dn 34",
    "filename": "en-dn34",
    "category": "dn",
    "filenr": 34
  },
  {
    "displayName": "Mūlapariyāya Sutta",
    "textname": "Mn 1",
    "filename": "en-mn1",
    "category": "mn",
    "filenr": 35
  },
  {
    "displayName": "Sabbāsava Sutta",
    "textname": "Mn 2",
    "filename": "en-mn2",
    "category": "mn",
    "filenr": 36
  },
  {
    "displayName": "Dhammadāyāda Sutta",
    "textname": "Mn 3",
    "filename": "en-mn3",
    "category": "mn",
    "filenr": 37
  },
  {
    "displayName": "Bhayabherava Sutta",
    "textname": "Mn 4",
    "filename": "en-mn4",
    "category": "mn",
    "filenr": 38
  },
  {
    "displayName": "Anaṅgaṇa Sutta",
    "textname": "Mn 5",
    "filename": "en-mn5",
    "category": "mn",
    "filenr": 39
  },
  {
    "displayName": "Ākaṅkheyya Sutta",
    "textname": "Mn 6",
    "filename": "en-mn6",
    "category": "mn",
    "filenr": 40
  },
  {
    "displayName": "Vattha Sutta",
    "textname": "Mn 7",
    "filename": "en-mn7",
    "category": "mn",
    "filenr": 41
  },
  {
    "displayName": "Sallekha Sutta",
    "textname": "Mn 8",
    "filename": "en-mn8",
    "category": "mn",
    "filenr": 42
  },
  {
    "displayName": "Sammādiṭṭhi Sutta",
    "textname": "Mn 9",
    "filename": "en-mn9",
    "category": "mn",
    "filenr": 43
  },
  {
    "displayName": "Mahāsatipaṭṭhāna Sutta",
    "textname": "Mn 10",
    "filename": "en-mn10",
    "category": "mn",
    "filenr": 44
  },
  {
    "displayName": "Cūḷasīhanāda Sutta",
    "textname": "Mn 11",
    "filename": "en-mn11",
    "category": "mn",
    "filenr": 45
  },
  {
    "displayName": "Mahāsīhanāda Sutta",
    "textname": "Mn 12",
    "filename": "en-mn12",
    "category": "mn",
    "filenr": 46
  },
  {
    "displayName": "Mahādukkhakkhandha Sutta",
    "textname": "Mn 13",
    "filename": "en-mn13",
    "category": "mn",
    "filenr": 47
  },
  {
    "displayName": "Cūḷadukkhakkhandha Sutta",
    "textname": "Mn 14",
    "filename": "en-mn14",
    "category": "mn",
    "filenr": 48
  },
  {
    "displayName": "Anumāna Sutta",
    "textname": "Mn 15",
    "filename": "en-mn15",
    "category": "mn",
    "filenr": 49
  },
  {
    "displayName": "Cetokhila Sutta",
    "textname": "Mn 16",
    "filename": "en-mn16",
    "category": "mn",
    "filenr": 50
  },
  {
    "displayName": "Vanapattha Sutta",
    "textname": "Mn 17",
    "filename": "en-mn17",
    "category": "mn",
    "filenr": 51
  },
  {
    "displayName": "Madhupiṇḍika Sutta",
    "textname": "Mn 18",
    "filename": "en-mn18",
    "category": "mn",
    "filenr": 52
  },
  {
    "displayName": "Dvedhāvitakka Sutta",
    "textname": "Mn 19",
    "filename": "en-mn19",
    "category": "mn",
    "filenr": 53
  },
  {
    "displayName": "Vitakkasaṇṭhāna Sutta",
    "textname": "Mn 20",
    "filename": "en-mn20",
    "category": "mn",
    "filenr": 54
  },
  {
    "displayName": "Kakacūpama Sutta",
    "textname": "Mn 21",
    "filename": "en-mn21",
    "category": "mn",
    "filenr": 55
  },
  {
    "displayName": "Alagaddūpama Sutta",
    "textname": "Mn 22",
    "filename": "en-mn22",
    "category": "mn",
    "filenr": 56
  },
  {
    "displayName": "Vammika Sutta",
    "textname": "Mn 23",
    "filename": "en-mn23",
    "category": "mn",
    "filenr": 57
  },
  {
    "displayName": "Rathavinīta Sutta",
    "textname": "Mn 24",
    "filename": "en-mn24",
    "category": "mn",
    "filenr": 58
  },
  {
    "displayName": "Nivāpa Sutta",
    "textname": "Mn 25",
    "filename": "en-mn25",
    "category": "mn",
    "filenr": 59
  },
  {
    "displayName": "Pāsarāsi Sutta",
    "textname": "Mn 26",
    "filename": "en-mn26",
    "category": "mn",
    "filenr": 60
  },
  {
    "displayName": "Cūḷahatthipadopama Sutta",
    "textname": "Mn 27",
    "filename": "en-mn27",
    "category": "mn",
    "filenr": 61
  },
  {
    "displayName": "Mahāhatthipadopama Sutta",
    "textname": "Mn 28",
    "filename": "en-mn28",
    "category": "mn",
    "filenr": 62
  },
  {
    "displayName": "Mahāsāropama Sutta",
    "textname": "Mn 29",
    "filename": "en-mn29",
    "category": "mn",
    "filenr": 63
  },
  {
    "displayName": "Cūḷasāropama Sutta",
    "textname": "Mn 30",
    "filename": "en-mn30",
    "category": "mn",
    "filenr": 64
  },
  {
    "displayName": "Cūḷagosiṅga Sutta",
    "textname": "Mn 31",
    "filename": "en-mn31",
    "category": "mn",
    "filenr": 65
  },
  {
    "displayName": "Mahāgosiṅga Sutta",
    "textname": "Mn 32",
    "filename": "en-mn32",
    "category": "mn",
    "filenr": 66
  },
  {
    "displayName": "Mahāgopālaka Sutta",
    "textname": "Mn 33",
    "filename": "en-mn33",
    "category": "mn",
    "filenr": 67
  },
  {
    "displayName": "Cūḷagopālaka Sutta",
    "textname": "Mn 34",
    "filename": "en-mn34",
    "category": "mn",
    "filenr": 68
  },
  {
    "displayName": "Cūḷasaccaka Sutta",
    "textname": "Mn 35",
    "filename": "en-mn35",
    "category": "mn",
    "filenr": 69
  },
  {
    "displayName": "Mahāsaccaka Sutta",
    "textname": "Mn 36",
    "filename": "en-mn36",
    "category": "mn",
    "filenr": 70
  },
  {
    "displayName": "Cūḷataṇhāsaṅkhaya Sutta",
    "textname": "Mn 37",
    "filename": "en-mn37",
    "category": "mn",
    "filenr": 71
  },
  {
    "displayName": "Mahātaṇhāsaṅkhaya Sutta",
    "textname": "Mn 38",
    "filename": "en-mn38",
    "category": "mn",
